# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OSRMroute <- function(FromDF, ToDF, OSRMdata) {
    .Call('OSRcppM_OSRMroute', PACKAGE = 'OSRcppM', FromDF, ToDF, OSRMdata)
}

OSRMrouteDF <- function(xlon, xlat, ylon, ylat, OSRMdata, measure = "distance") {
    .Call('OSRcppM_OSRMrouteDF', PACKAGE = 'OSRcppM', xlon, xlat, ylon, ylat, OSRMdata, measure)
}

